/*@![include:inc/lib/hubui/widget.js, compile]*/
/*@![include:inc/lib/hubui/utils.js, compile]*/
/*@![include:inc/lib/hubui/menu.js, compile]*/
/*@![include:inc/lib/hubui/renderer.js, compile]*/

/*@![include:inc/lib/hubui/widgets/button.js, compile]*/
/*@![include:inc/lib/hubui/widgets/canvas.js, compile]*/
/*@![include:inc/lib/hubui/widgets/color.js, compile]*/
/*@![include:inc/lib/hubui/widgets/datetime.js, compile]*/
/*@![include:inc/lib/hubui/widgets/dpad.js, compile]*/
/*@![include:inc/lib/hubui/widgets/gauge.js, compile]*/
/*@![include:inc/lib/hubui/widgets/icon.js, compile]*/
/*@![include:inc/lib/hubui/widgets/image.js, compile]*/
/*@![include:inc/lib/hubui/widgets/input.js, compile]*/
/*@![include:inc/lib/hubui/widgets/joy.js, compile]*/
/*@![include:inc/lib/hubui/widgets/label.js, compile]*/
/*@![include:inc/lib/hubui/widgets/led.js, compile]*/
/*@![include:inc/lib/hubui/widgets/plot.js, compile]*/
/*@![include:inc/lib/hubui/widgets/popup.js, compile]*/
/*@![include:inc/lib/hubui/widgets/select.js, compile]*/
/*@![include:inc/lib/hubui/widgets/slider.js, compile]*/
/*@![include:inc/lib/hubui/widgets/spinner.js, compile]*/
/*@![include:inc/lib/hubui/widgets/switch.js, compile]*/
/*@![include:inc/lib/hubui/widgets/tabs.js, compile]*/
/*@![include:inc/lib/hubui/widgets/text.js, compile]*/
/*@![include:inc/lib/hubui/widgets/title.js, compile]*/
