/*@![include:inc/lib/hubui/widget.js, compile]*/
/*@![include:inc/lib/hubui/utils.js, compile]*/
/*@![include:inc/lib/hubui/menu.js, compile]*/
/*@![include:inc/lib/hubui/renderer.js, compile]*/
/*@![include:inc/lib/hubui/widgets/button.js, compile]*/
/*@![include:inc/lib/hubui/widgets/label.js, compile]*/
/*@![include:inc/lib/hubui/widgets/led.js, compile]*/
/*@![include:inc/lib/hubui/widgets/icon.js, compile]*/
/*@![include:inc/lib/hubui/widgets/display.js, compile]*/
/*@![include:inc/lib/hubui/widgets/title.js, compile]*/
