
/*@![include:inc/widgets/render.js, compile]*/
/*@![include:inc/widgets/menu.js, compile]*/
/*@![include:inc/widgets/widget.js, compile]*/
/*@![include:inc/widgets/button.js, compile]*/
/*@![include:inc/widgets/label.js, compile]*/
/*@![include:inc/widgets/title.js, compile]*/
/*@![include:inc/widgets/plugin.js, compile]*/
/*@![include:inc/widgets/switch.js, compile]*/
/*@![include:inc/widgets/swicon.js, compile]*/
/*@![include:inc/widgets/display.js, compile]*/
/*@![include:inc/widgets/image.js, compile]*/
/*@![include:inc/widgets/table.js, compile]*/
/*@![include:inc/widgets/datetime.js, compile]*/
/*@![include:inc/widgets/popup.js, compile]*/
/*@![include:inc/widgets/log.js, compile]*/
/*@![include:inc/widgets/text.js, compile]*/
/*@![include:inc/widgets/input.js, compile]*/
/*@![include:inc/widgets/pass.js, compile]*/
/*@![include:inc/widgets/area.js, compile]*/
/*@![include:inc/widgets/slider.js, compile]*/
/*@![include:inc/widgets/spinner.js, compile]*/
/*@![include:inc/widgets/custom.js, compile]*/
/*@![include:inc/widgets/func.js, compile]*/
/*@![include:inc/widgets/select.js, compile]*/
/*@![include:inc/widgets/color.js, compile]*/
/*@![include:inc/widgets/led.js, compile]*/
/*@![include:inc/widgets/icon.js, compile]*/
/*@![include:inc/widgets/ui_file.js, compile]*/
/*@![include:inc/widgets/hook.js, compile]*/
/*@![include:inc/widgets/gauge.js, compile]*/
/*@![include:inc/widgets/gauge_r.js, compile]*/
/*@![include:inc/widgets/gauge_l.js, compile]*/
/*@![include:inc/widgets/joy.js, compile]*/
/*@![include:inc/widgets/dpad.js, compile]*/
/*@![include:inc/widgets/flags.js, compile]*/
/*@![include:inc/widgets/tabs.js, compile]*/
/*@![include:inc/widgets/canvas.js, compile]*/
/*@![include:inc/widgets/stream.js, compile]*/
/*@![include:inc/widgets/plot.js, compile]*/
